### ISSUE TITLE
Image file not displaying.

### ISSUE THREAD

**Issue by danielacav** [danielacav/mtm6201-week1#1]
Hello @abhaysharma 
I'm Daniela Cifuentes, enrolled in MTM 6201 - Web Dev. 

I'm embarrassed I'm having such silly problem, but while working in the GitHub Pages Repository assignment, I realized the image I provided is not displaying when I push everything in Github.

Can you please take a look at the code?. 
Thanks in advance.

**Comment by abhaysharma** [comment]
@danielacav  the issue is in the HTML file on line 15 the path needs to start with either ./images or just images. When you use /images it tries to go to the root of the GitHub repository.

**Comment by danielacav** [comment]
@abhaysharma Thank you so much!. All solved.
